export type RouteName =
  | '/'
  | 'mobile-development-projects'
  | 'mobile-development-projects/sneat'
  | 'mobile-development-projects/papott'
  | 'mobile-development-projects/docdok'
  | 'mobile-development-projects/opensource'
  | 'react-native-mobile-developer'
  | 'contact'
  | 'expertise'
